### PR TITLE
Added review for COMP3301

### PR DESCRIPTION
**Pull request by lsenjov**

### CODE REVIEW

**Comment by TRManderson** [comment]
Can one of the admins verify this patch?

**Comment by wisebaldone** [comment]
If you could add more about the contents of the course (what it actually teaches) and what resources u used / difficulties you reckon most people will have/words of advice.

**Comment by TRManderson** [comment]
I'll stop the bot posting as me soon

**Comment by wisebaldone** [comment]
LGTM, as per rules need total of 3 members to thumbsup

**Comment by CameronAavik** [comment]
I haven't done the course, but when you say the book is free online, is that offered by the authors/publishers? If it is, would we be able to get a link to that in there?

**Comment by CameronAavik** [comment]
Should we replace the thingo in preparation?

**Comment by wisebaldone** [comment]
I feel the review itself is more important than any other section of the template, Letting someone else contribute this part is fine by me.

**Pull request merged**
